# Generated by Django 4.1.4 on 2022-12-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='portafolio/img/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
